#spring.profiles.active: local
server:
  port: 9091
  ssl:
    enabled: false
    client-auth:

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    com.github.johnlayton.client: INFO
    com.github.johnlayton.client.app.handler: INFO
    com.github.johnlayton.client.app.router: INFO

spring:
  banner:
    image:
      location: "classpath:/logo.png"
      height: 25
      width: 40

management:
  endpoint:
    prometheus:
      enabled: on
    health:
      show-details: 'always'
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
      path-mapping:
        health: healthz
        prometheus: metrics
  server:
    port: 9092

client:
  amberleyway:
    address: http://localhost:8092/service/demo
